### ISSUE TITLE
Does not render?

### ISSUE THREAD

**Issue by jlnprssnr** [Maxsimuss/EngineSynth#5]
Stumbled upon this by pure luck, but sounds (heh) promising! Tried it by putting in some wav samples i found online, but it does not render (Four cylinders, nine samples). Or does it just take very long? But according to task manager, it is not doing anything. Save button works btw. Anything I can try?

**Comment by Maxsimuss** [comment]
Can you send me the samples you used?
Render should take just a few seconds on most hardware.

**Comment by jlnprssnr** [comment]
Ah it doesn't work with wav samples. I converted them to mp3 and now it worked! Though rendering took some seconds, so a progress indicator would be a nice addition :)
EDIT: nvm, my explorer just acted up because of OneDrive. Rendering was almost instant!

**Comment by jlnprssnr** [comment]
Follow-up question about strokes per revolution. Maybe you can add a button to calculate it for two stroke engine and four stroke engine based on cylinder count? Since from what I understand it's always = cylinder count for two stroke and = cylinder count / 2 for four strokes, right?

**Comment by Maxsimuss** [comment]
Progress bar will be added.
You are right about the stroke counts; I will add some presets for different kinds of engines.
Also, sorry for the late reply :)
